title: Formal Systems Laboratory
email: your-email@example.com

baseurl: "/fsl.cs.illinois.edu/"
url: "https://formal-systems-laboratory.github.io/"

# Build settings
plugins:
  - jekyll-feed

collections:
  - papers

